language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build