language: android

jdk:
  - oraclejdk8
  
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - android-25

 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'

before_install:
  - chmod +x gradlew
 
script:
  - ./gradlew build"
